latest

diff --git a/backup_restore b/backup_restore
--- a/backup_restore
+++ b/backup_restore
@@ -5,21 +5,26 @@
 # 
 # Version 1.0
 # tbartolone 30/06/2020
- set -x
+# set -x
 
 usage() {
+	init
 	PROGNAME=$0
 	cat <<- EOF
-	# lines must be indented with TAB
 
-	This script saves the logs collection for a given container
 	Missing arguments
-	$PROGNAME <archive full path> <project name> <suffix>
+	$PROGNAME <archive full path> <original project name> <new project name> <mode>
 
 	- suffix: project will be restored to <project>-<suffix>
-		- if empty, project will be restored simple to <project>
+		- if empty, project will be restored simply to <project>
 	
+	<mode> : dev or prod
+
 	EOF
+	clearmsg "\nList of archives in $backups_path"
+	for file in $(ls -1Atr $backups_path); do
+		readlink -m $backups_path/$file
+	done
 	exit 1
 }
 
@@ -31,6 +36,11 @@ init(){
 	timestamp=$(date +%Y%m%H%M)
 
 	. config.ini
+}
+
+clearmsg(){
+        msg=$1
+        printf "${CYAN}${msg}${NC}\n"
 }
 
 go(){
@@ -74,6 +84,28 @@ input_credentials(){
 	export new_password
 }
 
+generaldb_credentials_file(){
+        mode=$1
+        unset username
+        unset password
+        if [[ ! -f .${mode}_generaldb_creds ]]; then
+                echo "Credentials file cannot be found (.generaldb_creds)"
+                exit 1
+        fi
+
+        . ./.${mode}_generaldb_creds
+
+        username=${mode}_username
+        username=${!username}
+        password=${mode}_password
+        password=${!password}
+
+        if [[ -z $username ]] || [[ -z password ]]; then
+                echo "Credentials are empty (in .generaldb_creds)"
+                exit 1
+        fi
+}
+
 
 create_db_user(){
         command="CREATE DATABASE \`$project$suffix\`; SHOW DATABASES; CREATE USER \"$new_username\" IDENTIFIED BY \"$new_password\"; SELECT User FROM mysql.user; GRANT ALL PRIVILEGES ON \`$project$suffix\`.* TO \"$new_username\"; FLUSH PRIVILEGES; SHOW GRANTS FOR \"$new_username\";"
@@ -86,28 +118,41 @@ main(){
 	init
 
 	archive=$1
-	project=$2
-	if [[ -n $3 ]]; then
-		suffix="-$3"
-		echo "First please create project $project$suffix"
+	original_name_mode=$2
+	mode=${@: -1}
+
+	if [[ $# -eq 4 ]]; then
+		new_name=$3
+		clearmsg "First please create project $new_name in $mode mode"
+		new_name_mode=${new_name}-${mode}
+		read
 	else
-		suffix=''
+		new_name=''
 	fi
 
-	read
+
+	clearmsg "mode $archive project $project"
+
+	generaldb_credentials_file $mode
+	clearmsg "$username $password"
 
 	archive_name=$(basename $archive | sed 's/\.tgz//')
 	mkdir -p $restore_path/$archive_name
 	tar -xzf $archive --directory $restore_path/$archive_name
 
-	if [[ -n $suffix ]]; then
+
+	if [[ -n $new_name ]]; then
 		# Restore data
-		rm -rf $varwww_path/$project$suffix/wordpress/wp-content
-		mv $restore_path/$archive_name/$relative_varwww_path/$project/wordpress/wp-content $varwww_path/$project$suffix/wordpress
+		# we cannot delete and just copy the wordpress folder
+		# as we need to keep wordpress/wp-config.php
+		rm -rf $varwww_path/$new_name_mode/wordpress/wp-content
+		mv $restore_path/$archive_name/$relative_varwww_path/$original_name_mode/wordpress/wp-content $varwww_path/$new_name_mode/wordpress/
 	else
 		# Restore data
-		mv $restore_path/$archive_name/$relative_varwww_path/$project $varwww_path/$project$suffix
+		# In the case where we just restore the project, it is same wordpress folder
+		mv $restore_path/$archive_name/$relative_varwww_path/$original_name_mode $varwww_path/$original_name_mode
 	fi
+	exit
 	# Restore container config
 #	mv $restore_path/$archive_name/$relative_project_path/$project $project_path/$project$suffix
 #	sed -i "s/$project/$project$suffix/g" $project_path/$project$suffix/docker-compose.yml
